### ISSUE TITLE
Mod Testing Requests

### ISSUE THREAD

**Issue by Sirbucket** [IronOxidizer/FastAsFabric#1]
I'd like to leave a few mods for you to consider adding to the list. Putting this in issues because I'm not sure where the actual modpack is located if it's located anywhere besides your local PC.

All the provided mods should be completely compatable with what you have listed except FastBench and Starlight as it takes a different approach to phosphor to improve lighting (IE completely rewriting the engine instead of trying to fix it.)

[Sodium Extra](https://www.curseforge.com/minecraft/mc-mods/sodium-extra): Adds more options to sodium.

[Better Beds](https://www.curseforge.com/minecraft/mc-mods/better-beds): Updates the bed renderer to the 1.13 version from 1.12, increasing performance.

[Starlight](https://github.com/Spottedleaf/Starlight): Incompatable with Phosphor, completely rewrites the lighting engine, beating the vanilla engine and phosphors improvements multiple times over, still experimental.

[C2ME](https://github.com/YatopiaMC/C2ME-fabric): Improves the chunk generation, partially experimental.

[Recipe Cache](https://www.curseforge.com/minecraft/mc-mods/recipe-cache): Basically FastBench and FastFurnace wrapped into one mod.

[Dashloader](https://www.curseforge.com/minecraft/mc-mods/dashloader): Improves Minecrafts loading speed by caching loaded data the first time Minecraft is ran with the mod and will subsequently load faster afterwards.

[Lazy DFU](https://www.curseforge.com/minecraft/mc-mods/lazydfu): Causes DFU to load only when needed, drastically reducing minecraft resource usage upon booting and increasing the speed it boots at.

[No Fade](https://www.curseforge.com/minecraft/mc-mods/no-fade): Removes the fade animation upon finishing booting or reloading textures, no real performance improvement beyond getting you to the game slightly faster.

[No Weather Effects](https://www.curseforge.com/minecraft/mc-mods/no-weather-effects): Removes weather particles without removing their functionality, resulting in a performance boost with no change to minecraft behavior.

[Smoke Suppression](https://www.curseforge.com/minecraft/mc-mods/smoke-suppression): Blocks common in mob farms will stop camp fires from producing smoke, saving performance for an unnecessary feature for a mod farm (Usually camp fires will be used as effective mob farm spikes.)

[Client Side Noteblocks](https://www.curseforge.com/minecraft/mc-mods/client-side-noteblocks): Moves the noteblocks to the client side, greatly relieving lag in noteblock intense scenarios on servers and improving how noteblocks are handled in general.

These above mods improve performance directly, below however I'm going to include mods that provide bug fixes as I believe they are just as important.

[Auth Me](https://www.curseforge.com/minecraft/mc-mods/auth-me): Stops the minecraft authentication bug from forcing you to leave the game and rejoin.

[Dimension Fix](https://www.curseforge.com/minecraft/mc-mods/dimension-fix-some-forge-patches-ported): Stops removing a data pack dimension from removing the end and nether as well.

[Save My Stronghold](https://www.curseforge.com/minecraft/mc-mods/save-my-stronghold-fabric): Keeps the stronghold safe from outside terrain generation.

[Damage Tilt](https://www.curseforge.com/minecraft/mc-mods/damage-tilt): Restores directional damage indication that was broken in 1.3.1, causing it to always tilt to the left.

[AntiGhost](https://www.curseforge.com/minecraft/mc-mods/antighost): Removes ghost blocks within a radius around the player at the press of a button or use of command.

[Fabrication](https://www.curseforge.com/minecraft/mc-mods/fabrication): Comes with bugfixes that can all be toggled on and off and some optional gameplay tweaks that are not the main concern of this mod.

[Item Model Fix](https://www.curseforge.com/minecraft/mc-mods/item-model-fix): Removes the seams that appear on some minecraft items.

[ToolTipFix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix): Fixes long tooltips from going off screen.

[WhyAmIOnFire?](https://www.curseforge.com/minecraft/mc-mods/why-am-i-on-fire): Removes the fire overlay when affected by fire resistance or creative mode.

Potentially required library: [Fabric Language Kotlin](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)

These mods and more are listed on my list at https://github.com/Sirbucket/Fabric-Mod-Spotlight. Most are hosted on curseforge or github natively.

**Comment by IronOxidizer** [comment]
> I'm not sure where the actual modpack is located

Oops, forgot to add it to the readme
https://www.curseforge.com/minecraft/modpacks/fast-as-fabric

- Sodium Extra: Will test
- Better Beds: Will test
- Starlight: Will test, replaces phosphor
- C2ME: Will test
- Recipe Cache: Will test, replaces fast bench + fast furnace
- Dashloader: Will test
- Lazy DFU: Will test
- No Fade: Already included in Fast-as-Fabric
- No Weather Effects: Overlapping functionality with Sodium Extras
- Smoke Suppression: Will test, partially overlapping with Sodium Extras
- Client Side Noteblocks: Will test

Bug fixes and QoL mods are not the focus of Fast as Fabric. They increase bloat, may contain additional dependencies, and may not be welcome to everyone using this pack. These are the kinds of mods that should be included by Vanilla+ packs based on FaF.

**Comment by Sirbucket** [comment]
Alrighty, sodium extra simply allows you to toggle more, I didn't realize no fade was, no weather effects I thought wasn't, smoke suppression is different, smoke suppression effects the smoke rendering if the campfire is touching blocks in farms, so if you want camp fire particles but not in your mob farms, it's a great performance option.

**Comment by Sirbucket** [comment]
And yeah the bugfixes are ok to not include, I just tend to find bugfixes and performance improvements usually go hand in hand in improving the user experience.

**Comment by IronOxidizer** [comment]
> no weather effects I thought wasn't, smoke suppression is different, smoke suppression effects the smoke rendering if the campfire is touching blocks in farms

Understood. I noticed that Sodium Extras has a greater ability to disable effects, animations, and particles than sodium, including weather and smoke so I'll test it. As for Smoke Suppression, I see the value in having it be enabled / disabled dynamically, but the disabling functionality is already overlapping with Sodium Extras, as such, seems more like a QoL mod in this context, I've been thinking of removing `Cull Leaves` from my pack for similar reasons, though, I'll keep both in consideration for now. I've updated my comment to reflect this.

There's a good chance I won't test these till 1.17 though as it's right around the corner and I've been pretty busy with work recently.

**Comment by IronOxidizer** [comment]
Thanks for bringing these mods to my attention too. I thought I had found all of them, but I'm glad there are even more ways to improve minecraft.

**Comment by Sirbucket** [comment]
Yeah there's a few more I think, there's one that optimizes hoppers, however lithium seems to tackle that in 1.17 so I say that's something to be ignored.

**Comment by Sirbucket** [comment]
It's mainly a performance setting for if you want to have campfire smoke but you don't want it to be inside your farms causing insane lag.

**Comment by Sirbucket** [comment]
https://github.com/2No2Name/hopperOptimizations/releases is being merged with lithium in 1.17

**Comment by Sirbucket** [comment]
If you want to see a good example of making a performance configuration archetype, https://github.com/mastercomfig/mastercomfig/ is a great example, prioritizes fixing bugs and improving performance.

**Comment by Sirbucket** [comment]
This is for TF2 but it uses principles that can be applied to all games.

**Comment by Sirbucket** [comment]
Obviously this is a base so it should be lightweight and mostly stable, but when I create bases for anything I tend to like to make sure it fixes problems with the base game so no matter what you use it for you don't have to manually fix anything and you can just add the content mods you want.

**Comment by Sirbucket** [comment]
Upon examining Krypton's source code and it's change log https://github.com/astei/krypton/commits/master it does in fact improve performance, it's just very low level tweaks and is mostly a resource saver and not a large performance improvement, however it is probably worth adding, even if there is no framerate increase just due to making the code more efficient overall.

**Comment by IronOxidizer** [comment]
> Upon examining Krypton's source code and it's change log, it does in fact improve performance

I don't doubt it improves performance, I just haven't seen any benchmarks or evidence to verify the theoretical improvements. 

If the improvements are so small that it's immeasurable by any metric, then it's hard to justify the bloat of adding another dependency to manage, test, and bundle into the pack.
