### ISSUE TITLE
Remove Simplex Terrain Generation and add Overworld Two

### ISSUE THREAD

**Issue by Sirbucket** [IronOxidizer/FastAsFabric#6]
Simplex just seems to change terrain generation and not improve performance directly, Overworld Two also changes terrain generation but keeps it vanilla friendly even if it does not maintain vanilla parity, it directly aims to improve terrain generation performance.

**Comment by IronOxidizer** [comment]
Resolved by https://github.com/IronOxidizer/Fast-as-Fabric/commit/1540ddeca91e7653542c900b3a79926cf353060c
