### ISSUE TITLE
Replace Fast Furnace and Fast Bench with Recipe Cache

### ISSUE THREAD

**Issue by IronOxidizer** [IronOxidizer/FastAsFabric#7]
- Fast Furnace's fuel caching is fixed with https://github.com/FabricMC/fabric/pull/1108
- Fast Furnace's recipe caching is handled by Recipe Cache
- Fast Bench's recipe caching is handled by Recipe Cache

**Comment by Sirbucket** [comment]
It also opens the door for more than just the furnace and workbench being cached.
